### PR TITLE
Adding bedrock reinforcement

### PR DESCRIPTION
**Pull request by Maxopoly**
@rourke750 

Can I just merge this or do I need to do anything else? That's for jacky.

### CODE REVIEW

**Comment by ttk2** [comment]
is it safe to use int_max exactly? Should we subtract a couple hundred from it to be safe?

**Comment by Maxopoly** [comment]
It's int_max -1, in theory we should be safe, but we might as well just subtract a couple hundred if rourke thinks there are any possible issues.

**Comment by rourke750** [comment]
@Maxopoly It would be more of an @erocs question.  I dont have a very good understanding of the undergoings of programming.

**Comment by erocs** [comment]
Why is a bedrock reinforcement being added? Set maturity to 0?
The hit_points should be fine.

**Comment by ttk2** [comment]
for admin stuff in new shards.

**Comment by rourke750** [comment]
We want the maturation to be at least higher than diamond so no one can reinforce it.  It might be a good idea to add a new option in the config and specify which reinforcements can be used to acid block it.

**Comment by erocs** [comment]
There should be a hard coded prevention against acid blocking bedrock and
ender portal blocks. Or at least there was in 2.0...

N

**Comment by Maxopoly** [comment]
There already is a prevention against acidblocking bedrock, but I dont see how that's relevant here. 

Reinforcements reinforced with bedrock, could only be acidblocked with bedrock reinforced acidblocks and obviously noone is gonna have those, thats a non-issue as long as we leave the maturation higher than the diamond maturation.

**Comment by erocs** [comment]
I was attempting to figure out why maturation even maters. I may have
slightly mis-read Rourke's text, but the only place where it should matter
is with acid blocks. Of course, Citadel3 is different in weird ways from 2
so go forth and change it.

**Comment by rourke750** [comment]
Citadel 3.0 also allows scale damaging based on maturation so that's why it
matters, also with acid blocks.

**Comment by Maxopoly** [comment]
So how should I change it? Right now maturation_time is INT_MAX -1

**Comment by ttk2** [comment]
bumping for @rourke750

**Comment by rourke750** [comment]
This is all good. @Maxopoly Merge whenever you feel.

**Pull request merged**
