### PR TITLE
Re-add Group Reinforcement Count

### PR DESCRIPTION
**Pull request by clone2204**
Changes to Citadel plugin, Changes to Namelayer also required.

These changes allow for groups to keep track of how many reinforcements
of each type are under that group. The groups will now keep track of the
number, and now only incriment or decriment from that number when a
reinforcement is added or removed from the DB.

### CODE REVIEW

**Comment by rourke750** [comment]
You need to fix your commit history.  I have no idea what is being changed.

**Comment by jjj5311** [comment]
this is a cluster if i have ever seen one, i think you should rebase and try again

**Comment by clone2204** [comment]
I still don't know how ;-; Github is hard.

**Comment by jjj5311** [comment]
https://help.github.com/articles/syncing-a-fork/

**Comment by jjj5311** [comment]
that was the wrong link, but you can google it and there is tons of guides

**Pull request closed without merging**
