### PR TITLE
Rework permissions

### PR DESCRIPTION
**Pull request by Maxopoly**
Let's Citadel use the new functionality added with https://github.com/Civcraft/NameLayer/pull/191

Should be merged after the NameLayer PR is merged.

### CODE REVIEW

**Comment by ProgrammerDan** [comment]
Besides the build failing looks ok.

**Comment by Maxopoly** [comment]
Well the build is failing, because it doesnt have the updated NameLayer version yet.

**Comment by ProgrammerDan** [comment]
I figured that might be the case.

**Comment by Maxopoly** [comment]
Or actually it's not. I kicked out public groups after making this and changed some packetnames because of that, so I need to adjust that here.

**Pull request merged**
