### PR TITLE
Instrumenting proper logging for player actions

### PR DESCRIPTION
**Pull request by ProgrammerDan**
Finishing up some basic listeners for player interactions with reinforcements

Cleaned up logging and added more, continuing to work through and clean up codebaes

Cleanup continued with only listeners left and cleanup testing of cleanup.

Adding proper player command _response_ logging, fixes. I think this is largely it for Citadel improvements for now.

Adding command to allow live updating of internal logging.

Fixes based on Zion livetest, works, adjusted logging levels appropriate and have sensible defaults.

### CODE REVIEW

**Comment by ProgrammerDan** [comment]
Obviously a lot of changes. Tested on Zion, working.

Gives much better insight into what's going on within Citadel.


Introduces the /ctsl command to set the new logging on or off. 

E.g. /ctsl internal off  -- turns internal logging off. /ctsl reinforcement on would turn reinforcement creation logging on (gets spammy, I don't recommend leaving it on).

**Comment by ProgrammerDan** [comment]
ok to test

**Comment by ProgrammerDan** [comment]
ok to test

**Comment by ProgrammerDan** [comment]
Oh, woops, using java 1.8 methods and all our builds are 1.7

Note to self: https://github.com/Civcraft/Citadel/pull/174/files#diff-9471da9260a340fcf2e3f1f6c1af8bc9R69

**Comment by rourke750** [comment]
Update pom to 1.8. We are using that anyways.

**Comment by ProgrammerDan** [comment]
Works for me.

**Comment by ProgrammerDan** [comment]
Looks like jenkins doesn't have java 8?

**Comment by ProgrammerDan** [comment]
ok to test

**Comment by ProgrammerDan** [comment]
ok to test

**Comment by ProgrammerDan** [comment]
I think I'm just going to merge this. We'll do it live. Need solid testing data to know if its working or not anyway. I'll prep the configs per shard.

**Pull request merged**
