### PR TITLE
Fix #88 and #89

### LINKED ISSUE #88: reinforced farmland
reinforcing the farmland does not pass the reinforcement along to crops like it used to, letting water flow and pop crops off, as in i used to be able to reinforce the farmland plant a crop on the farm land and water could not pop off the crop, now it does

### LINKED ISSUE #89: Provide group id in admin version of /cti
Today the admin version of /cti shows the group name, but with NameLayer groups this could map to any number of group IDs. Please add the group number to the information.

### PR DESCRIPTION
**Pull request by jjj5311**
~~Fix #89 with ... Also requires a small change to NameLayer~~
~~https://github.com/Civcraft/Citadel/commit/c3d4738900fef8b145b4c7bef321b68ddab08b16~~

Fix #88 with 
https://github.com/Civcraft/Citadel/commit/d27aec72184bbb9cb6d15c485a15abea5fda4fc0

### CODE REVIEW

**Comment by ttk2** [comment]
civtest?

**Comment by rourke750** [comment]
pls

**Comment by rourke750** [comment]
@ttk2 Also NameLayer pls

**Comment by ttk2** [comment]
on Civtest, sorry for the dely

**Pull request merged**
