### PR TITLE
Fix NameLayer #62 remove ctf/ctr when player is demoted

### PR DESCRIPTION
**Pull request by jjj5311**

### CODE REVIEW

**Comment by spaceFountain** [comment]
This looks good, but it might be worth in the future checking the PlayerState to see if the update will affect it? I can see an possibility for abuse where the player is kept from breaking blocks or using citadel by someone who has them in a group shuffling their level.

We may also want to consider what happens when the permissions for a level change. AKA members can no longer reinforce or break blocks.

**Comment by jjj5311** [comment]
The event in namelayer only fires if they were Mod or above and were moved to member or below, I don't know if that would be enough or not

https://github.com/jjj5311/NameLayer/blob/30342d902da13d2feac6a5bc8795972df2d2f915/src/vg/civcraft/mc/namelayer/command/commands/PromotePlayer.java#L116-124

**Comment by spaceFountain** [comment]
The things is the owner of a group can change the privileges he gives to each level. He can remove the ability of mods to do anything or give members the same power as mods. [This](https://github.com/Civcraft/Citadel/blob/master/src/vg/civcraft/mc/citadel/command/commands/Fortification.java#L54-L57) is the check that actually determines if someone has the ability to reinforce blocks. Maybe redoing that check and then resetting the state if need would be better behavior?

**Comment by jjj5311** [comment]
Created new pull so someone couldnt knock someone out of /ctf /ctr just by adding them to a group and /nlpp up and down

**Pull request closed without merging**
