### PR TITLE
Fixing typo in reinforcement mode enum

### PR DESCRIPTION
**Pull request by Maxopoly**
@rourke750  @erocs 

Can we just do that or does this affect something else I'm not aware of?

### CODE REVIEW

**Comment by Maxopoly** [comment]
ok to test

**Comment by Maxopoly** [comment]
bump

**Comment by erocs** [comment]
Should be fine.

**Comment by ProgrammerDan** [comment]
I'm surprised this can still merge cleanly. Not opposed.

**Pull request merged**
