### PR TITLE
Fix issue with quietly exiting reinforcement mode

### PR DESCRIPTION
**Pull request by jjj5311**
Also add in extra logging for exceptions in blocklistener

#113

### CODE REVIEW

**Comment by ProgrammerDan** [comment]
Looks good, nothing else is coming to mind.

**Comment by gipsy-king** [comment]
Looks good.

**Comment by ttk2** [comment]
ok to test

**Comment by ttk2** [comment]
on civtest, test it out.

**Comment by ttk2** [comment]
does this need its own testing thread?

**Comment by jjj5311** [comment]
No nothing to effect gameplay really just another message to players to
avoid confusion.

**Pull request merged**
