### PR TITLE
Fixed an issue where TealNerd is a lying little bitch

### PR DESCRIPTION
**Pull request by TealNerd**
removed a couple invalid imports so it should build now

### CODE REVIEW

**Comment by ttk2** [comment]
Funny, but descriptive merges are kinda important.

**Comment by TealNerd** [comment]
sorry, removed a couple imports because i was stupid and screwed it up before

**Comment by TealNerd** [comment]
@ttk2 this should fix the issue causing it not to build

**Comment by ttk2** [comment]
that's better, merged.

**Pull request merged**
