### PR TITLE
Fix #74 reinforced dirt/soil does not reinforce the crops

### LINKED ISSUE #74: Reinforced dirt doesn't reinforce associated crops
https://www.reddit.com/r/Civcraft/comments/2x3wi1/morning_changelog_20150225/cowmxfm

"This may or may not be the right place...
Under Citadel 2.0, if we reinforced the ground underneath crops, it would cause the crops that grew to be reinforced, too.
This no longer seems to be the case in 3.0 (at least, not on the stuff that was reinforced before the change)
Is this by design?"

### PR DESCRIPTION
**Pull request by jjj5311**
# Fix issue #74 

* Config.yml 
  * changed on accident

* Utility.java
  * Added in method to get the soil block for a plant

* BlockListener
  *  updated OnBlockBreak event to check if a crop and if so use the reinforcement of the soil for the crop

* Testing (For morning changelog so people know what to do)
  *  Testing needs to be done with all crops potatoes, wheat, carrots, netherwart, sugarcane, melon stems, pumpkin stems
  *  to do the tests create reinforced dirt/soil/whatever the crop requires and then plant the seed
  *  confirm that when no CROPS permission it takes the right amount of breaks to get the crop
  *  confirm that with CROPS permission for the group the plant drops as it would if it weren't reinforced
  *  confirm reinforcing Melon blocks and pumpkin blocks still works like regular blocks

### CODE REVIEW

**Comment by WildWeazel** [comment]
What happened with that first commit? 484b7e77e803e4aec9f2169cd14a172642563de1

**Comment by jjj5311** [comment]
hmm, no idea

i was trying to sync my fork with this civcraft/master

**Comment by WildWeazel** [comment]
In findPlantSoil shouldn't it return null immediately if it finds a block that isn't either soil or the plant itself?

**Comment by WildWeazel** [comment]
@ttk2 http://192.99.169.83:8080/job/Citadel-master/94/ Civtest

**Comment by jjj5311** [comment]
Yeah that would be a good improvement

**Comment by Akiyama64** [comment]
Currently testing if a stranger can harvest crops that have dirt reinforced under them. Used "/nlmp AkiTest remove OWNER CROPS" and have the following:

TNT will still break plants if the plant itself is not reinforced. Dirt blocks alone aren't good enough.

With crops permission removed, all crops cannot be easily trampled by people without permissions when reinforced. (It takes at least 25 jumps on a reinforced block of tilled dirt to trample it.) If there is no plant in the tilled soil, then the soil can be quickly trampled by adding something like a dirt block on top of the tilled soil. (Suffocation of tilled soil.)

Harvesting is still possible when permission to do so is removed. All a moderator or someone higher has to do is use /ctb. (Kind of obvious, but strangers in civcraft aren't going to be moderators of such a farm reinforcement group.)
ISSUE: Using ctb to harvest in such a situation destroys the reinforcement of the dirt block which the plant grew on. Players are suggested to never use ctb to harvest their own crops.

With stone reinforced dirt, crops take 25 hits to break and drop their goods with CROPS off. This action gets rid of the reinforcement of the block below.
With reinforced dirt protecting the crops, I could not harvest the following after removing the CROPS permission: Carrots, potatoes, wheat, pumpkin stem, melon stem, sugarcane, and netherwart. When CROPS was turned on, all harvesting was normal. I could pick whatever I wanted.

As for reinforcement on the blocks of melons and pumpkins, with my CROPS Permission and ctb off, I could break the melon and pumpkin blocks in one break each. Thus, melon and pumpkin blocks DO NOT behave like normal reinforced blocks when they are reinforced.

That issue with melon and pumpkin blocks could be a problem for some farms in Civcraft.

Interestingly, TNT does not destroy melon and pumpkin blocks that are reinforced. Without using ctb, I can still break such pumpkin and melon blocks in one hit, even if CROPS is off. In contrast, TNT will break every plant and stem on tilled dirt unless the plant or stem itself is reinforced (reinforced dirt is not enough).

I would say that pumpkin and melon blocks are not behaving as they should, and TNT behaves abnormally on all crops. TNT will destroy plants when the dirt is reinforced unless the plant itself is reinforced (which is impossible for wheat, for example).

**Pull request merged**
