### PR TITLE
Fix for Pistons

### PR DESCRIPTION
**Pull request by BlackXnt**
I tested it, seems to be working. More testing should be done on civtest.

### CODE REVIEW

**Comment by WildWeazel** [comment]
ok to test

**Comment by WildWeazel** [comment]
http://192.99.169.83:8080/job/Citadel-master/132/

**Comment by rourke750** [comment]
@ttk2

**Comment by ttk2** [comment]
on civtest, staged for tomorrow.

**Comment by BlackXnt** [comment]
Ok I did more testing on civtest and everything is working. This change also fixes the old problem with normal piston not retracting after touching a reinforced block.

**Comment by ttk2** [comment]
sounds great, its staged for restart, thanks a ton!

**Comment by ttk2** [comment]
you are in the dev group now right?

**Comment by BlackXnt** [comment]
I am in the github dev group someone made a few days ago, not sure if there are any other groups.

**Comment by ttk2** [comment]
there is a google email group, do you want an invite?

**Comment by BlackXnt** [comment]
Sure, my email: blackxnt@gmail.com.

**Pull request merged**
