### PR TITLE
Working version of Acid Timer (Do not Merge Yet, Testing required)

### PR DESCRIPTION
**Pull request by ProgrammerDan**
Also rebased against latest master. Going to deploy on devoted and time the DB upgrade, to give counsel if this is a safe upgrade for Civcraft or no.

In any case it'll be a null change for civ's behavior. I'll be testing that to be certain against CivTest.

### CODE REVIEW

**Comment by ttk2** [comment]
ok to test

**Comment by ProgrammerDan** [comment]
I still have to push this to Civtest for a civ-safe test, but it's been running on Devoted all week and no issues so far, so that's a plus.

**Comment by ttk2** [comment]
Merge at will then.

**Comment by ProgrammerDan** [comment]
@ttk2 Note: The DB upgrade took 5 seconds with 267,000 entries for Devoted. Should be linear, in terms of estimating time for upgrade for Civcraft if this goes online.

**Comment by ttk2** [comment]
that's going to be fun, might not bother with it.

**Comment by ProgrammerDan** [comment]
Well, I'm content to keep this as a non-merging feature branch, if there's no genuine interest in ever using split acid and block maturation times.

Be a bit of a pain in the ass for me to keep things organized, but no skin off Civ's back :D.

If that's the case though, I will apply my last commit selectively against master as without it, Citadel will break in a terrible way. I learned this by experience, hehe.

**Comment by ttk2** [comment]
no go ahead and merge it.

**Comment by rourke750** [comment]
@ProgrammerDan All features are good.  Getting people to merge any changes that are positive are looked forward to.  Also I'm pretty sure we have a faster machine then devoted so it might be quicker.  Thanks for the changes though.

**Comment by ShadedJon** [comment]
Current machine has these specs:

CPU:	Intel Atom C2758 2.40GHz
RAM:	8GB
Hard drive(s):	2x 120GB SSD

So yeah, most likely.

Is this the build I tested for you Dan? Don't want this fix to get forgotten about

**Comment by ProgrammerDan** [comment]
Yes it is. Looks like I need to rebase it before I can merge it though :)

**Comment by ProgrammerDan** [comment]
Closing, way out of sync.

**Pull request closed without merging**
