### PR TITLE
Add perc

### PR DESCRIPTION
**Pull request by ProgrammerDan**
From @Vastitas  --  allows optional display of health as a percent instead of just poor/well etc.

### CODE REVIEW

**Comment by rourke750** [comment]
The current system is intentional. Is this configurable?

**Comment by Maxopoly** [comment]
Could you change the default in the config and internally to false?

**Comment by ProgrammerDan** [comment]
Ah yeah, my bad, meant to change it to default "false". 

@rourke750 Totally configurable. Easily disabled.

**Comment by ProgrammerDan** [comment]
I'll rebase.

**Comment by Maxopoly** [comment]
Do you want to rebase or should we just merge this?

**Comment by ProgrammerDan** [comment]
rebased. if build is good should be good to merge.

**Pull request merged**
