### PR TITLE
Rebased sketch of splitting out acid timer as a separate thing. 

### PR DESCRIPTION
**Pull request by ProgrammerDan**
Updated for latest changes. Should work fine on civ-main-stream servers; anyone who used the prior fork or Devoted's fork will not have a smooth upgrade.

Doesn't impact CivCraft's master, though, this merge should be clean and upgrade clean.

### CODE REVIEW

**Comment by ttk2** [comment]
so this separates acid and maturation?

**Comment by ProgrammerDan** [comment]
Yeah, same as the prior pull just rebased to latest. We'd agreed to merge it but I forgot to push the button :)

**Comment by ProgrammerDan** [comment]
For reference, prior pull was https://github.com/Civcraft/Citadel/pull/149

**Comment by ttk2** [comment]
it is done.

**Pull request merged**
