### PR TITLE
Fixing some ghost blocks

### PR DESCRIPTION
**Pull request by ProgrammerDan**
Cleaning up some code that can cause "ghost" reinforcements.

### CODE REVIEW

**Comment by ProgrammerDan** [comment]
@Erocs Should be better, thanks for the suggestion. 

@Rourke750 indicates there's another area to fix; I'll catch that in a pull later as it will require further testing.

**Comment by ProgrammerDan** [comment]
Build is on civtest.

**Comment by ProgrammerDan** [comment]
LOL, oh man. I need to start sleeping again.

**Comment by erocs** [comment]
Sleep is for the weak, or at least that's what I tell myself every morning at 4.

**Comment by ProgrammerDan** [comment]
With some luck, perhaps that did it. Man, batting 1000 today.

**Comment by erocs** [comment]
Seems legit.

**Comment by ProgrammerDan** [comment]
weird that clahub is complaining, definitely signed it. In any case, it's up on civtest (x3)

**Comment by ProgrammerDan** [comment]
initial testing indicates the fix is good.

@ttk2 your discretion, can stage this fix now or wait for me to investigate the other bit Rourke wants; that might take longer.

**Comment by rourke750** [comment]
Ttk u can stage.

**Comment by erocs** [comment]
Staged

**Comment by erocs** [comment]
http://build.civcraft.co/job/Citadel-master/192/artifact/target/Citadel-3.3.5.jar

**Comment by ttk2** [comment]
oh hey this is whats causing restart to hang

**Comment by ProgrammerDan** [comment]
That doesn't make sense. This code change is 100% passive and only impacts the execution of /ctacid -- nothing else, no database changes, and it definitely doesn't check for Ghost blocks.

So unless there's another upstream patch that went out, _this_ patch for sure isn't causing the hang.

**Pull request merged**
