### PR TITLE
Areareinforcements for admins

### PR DESCRIPTION
**Pull request by Maxopoly**
Admin crime tool   @rourke750  could you review this, please?

### CODE REVIEW

**Comment by Maxopoly** [comment]
ok to test

**Comment by rourke750** [comment]
ok to test

**Comment by rourke750** [comment]
Looks good, did you test locally?  Also I'll add you to the pull request thing later.

**Comment by Maxopoly** [comment]
I didn't test it locally, I can't get some of the dependencies to resolve, so I just wanted to test it with a build from Jenkins.
It didn't even compile in Jenkins, seems like I forgot a few imports, I'll fix that later and then test it.

**Comment by Maxopoly** [comment]
Okay I changed this so it doesn't consume materials anymore (it's op only anyway) and cleaned up the pull a bit. Already tested it on civtest and works exactly as intended, I'll merge it.

**Pull request merged**
