### PR TITLE
fix issue with acid blocks

### LINKED ISSUE #108: Acid blocks usuable by members of same group?

### PR DESCRIPTION
**Pull request by jjj5311**
Fix #108

### CODE REVIEW

**Comment by drjawa** [comment]
ok to test

**Comment by drjawa** [comment]
Oh, you also need to sign the CLA.

https://www.clahub.com/agreements/Civcraft/Citadel

**Comment by jjj5311** [comment]
done

**Comment by drjawa** [comment]
Putting on civtest once its done building

**Pull request merged**
