### PR TITLE
Fix Acid block event

### PR DESCRIPTION
**Pull request by ghost**
The AcidBlockEvent class had a misnamed method and also didn't provide an accessor to get the player associated with the event.

### CODE REVIEW

**Review by ProgrammerDan — COMMENTED** [review]
Unfortunately this would break every current consumer of the api. There are several (including some of my plugins...)

**Comment by CivFactions** [comment]
do I keep the typo then?

**Comment by ProgrammerDan** [comment]
Perfect.

**Comment by ProgrammerDan** [comment]
Ok last thing, just increment the version in the pom

**Comment by CivFactions** [comment]
added

**Comment by ProgrammerDan** [comment]
Looks like you need to rebase this against latest.

**Comment by CivFactions** [comment]
interesting. idk how my fork got so out of date. It should be fixed now though.

**Comment by ProgrammerDan** [comment]
Eh, it happens :D

**Comment by ghost** [comment]
thanks

**Pull request merged**
